<footer>
    <nav id="bottomnavigation">
        <a href="index.html">Home</a> |
        <a href="contact.html">Contact</a> |
        <a href="techzone.html">TechZone</a> |
        <a href="join.php">Join</a> |
        <a href="moviezone.html">MovieZone</a><br>
    </nav>
    <div id="contact">
        <h1>Contact Us</h1>
        <img src="images/facebook-logo.png" alt="Follow us on Facebook" class="socialicon">
        <img src="images/instagram-logo.png" alt="Follow us on Instagram" class="socialicon">
        <img src="images/twitter-logo.png" alt="Follow us on Twitter" class="socialicon">
        <ul id="contactdetails">
            <li>Email: <a href="mailto:jdoher10@gmail.com">contact@edgeoftomorrowdvdrentals.com</a></li>
            <li>Website: <a href="http://infotech.scu.edu.au/~jdoher10/" target="_blank">http://infotech.scu.edu.au/~jdoher10/</a></li>
        </ul>
    </div>
    <p class="copyrightnotice">
        All content &copy; 2017 Jennifer Doherty except as noted. DISCLAIMER: This website is for educational purposes only. All copyrighted content belongs to the copyright owners.
    </p>
</footer>