<header>
   <div id="logo"> <!-- CSS logo definition -->
      <div id="logobackground">
         <div id="logoshape">
            <div id="logotext">
               <h1>Edge of Tomorrow<br>DVD Rentals</h1>
            </div>
         </div>
      </div>
   </div>
</header>

<nav id="leftnavigation">
   <ul class="leftnavigationparent">
      <li><a id="indexNav" href="index.php">Home</a></li>
      <li><a id="contactNav" href="contact.php">Contact</a></li>
      <li><a id="techzoneNav" href="techzone.php">TechZone</a></li>
      <li><a id="joinNav" href="join.php">Join</a></li>
      <li><a id="moviezoneNav" href="moviezone.php">MovieZone</a></li>
   </ul>
</nav>